### ISSUE TITLE
bold option for those who want bold ios text

### ISSUE THREAD

**Issue by myysty** [SlippingGitty/surCord#9]
idk how to suggest shit but, yeah

**Comment by SlippingGitty** [comment]
## Sure!

### Step 1

Navigate to `_modules.scss` 
![image](https://user-images.githubusercontent.com/76500838/177686608-9dc620f4-1e87-41d3-97f6-5e558641b9e9.png)

### Step 2

Find the `/* Fonts */` comment in the file, it should look like this:

![image](https://user-images.githubusercontent.com/76500838/177685822-0c17b203-46a1-4340-bb5f-ae9ba43186a4.png)

### Step 3

To enable bold text, uncomment `//font-weight: bold;` by removing the slashes so that it reads as 
`font-weight: bold;`. Make sure that you are doing this under your respective platform's class (`.platform-osx` or `.platform-linux, .platform-win`).

It should look similar to this:
![image](https://user-images.githubusercontent.com/76500838/177686855-e63b10c6-74c5-4b24-9557-a03d3c44dfc1.png)

### Step 4 

Profit!

![image](https://user-images.githubusercontent.com/76500838/177687565-ae198bab-30d3-449e-b954-c867b83e72e9.png)
